/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eje_calculadora;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.script.ScriptException;
import javax.swing.JOptionPane;

/**
 *
 * @author mutsu
 */


public class frm_calculadora extends javax.swing.JFrame {

    private String cadenaNumeros = "";
    private String operacion = "nula";
    private double primerNumero, resultado;
    private boolean activado = true;
    private boolean punto = true;
    private boolean inicio=true; 
    
  ScriptEngineManager  sem = new ScriptEngineManager();
  ScriptEngine se = sem.getEngineByName("JavaScript");
   boolean decimal=false;  
   
    public frm_calculadora() {
        initComponents();
        inicio=true;
        setLocationRelativeTo(null);
        
      
       
           
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_resu = new javax.swing.JButton();
        btn_punto1 = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_multipli = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_r = new javax.swing.JLabel();
        txt_r1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtresultado = new javax.swing.JLabel();
        txtoperacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_1.setBackground(new java.awt.Color(0, 0, 0));
        btn_1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setText("1");
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_1MouseReleased(evt);
            }
        });
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        btn_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_1KeyReleased(evt);
            }
        });
        jPanel1.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 50));

        btn_2.setBackground(new java.awt.Color(0, 0, 0));
        btn_2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setText("2");
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_2MouseClicked(evt);
            }
        });
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 50, 50));

        btn_3.setBackground(new java.awt.Color(0, 0, 0));
        btn_3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setText("3");
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_3MouseClicked(evt);
            }
        });
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 50, 50));

        btn_4.setBackground(new java.awt.Color(0, 0, 0));
        btn_4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setText("4");
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_4MouseClicked(evt);
            }
        });
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 50));

        btn_5.setBackground(new java.awt.Color(0, 0, 0));
        btn_5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_5.setForeground(new java.awt.Color(255, 255, 255));
        btn_5.setText("5");
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_5MouseClicked(evt);
            }
        });
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 50));

        btn_6.setBackground(new java.awt.Color(0, 0, 0));
        btn_6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_6.setForeground(new java.awt.Color(255, 255, 255));
        btn_6.setText("6");
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_6MouseClicked(evt);
            }
        });
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, 50));

        btn_7.setBackground(new java.awt.Color(0, 0, 0));
        btn_7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_7.setForeground(new java.awt.Color(255, 255, 255));
        btn_7.setText("7");
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_7MouseClicked(evt);
            }
        });
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 50));

        btn_8.setBackground(new java.awt.Color(0, 0, 0));
        btn_8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_8.setForeground(new java.awt.Color(255, 255, 255));
        btn_8.setText("8");
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_8MouseClicked(evt);
            }
        });
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, 50));

        btn_9.setBackground(new java.awt.Color(0, 0, 0));
        btn_9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_9.setForeground(new java.awt.Color(255, 255, 255));
        btn_9.setText("9");
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_9MouseClicked(evt);
            }
        });
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 50));

        btn_0.setBackground(new java.awt.Color(0, 0, 0));
        btn_0.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_0.setForeground(new java.awt.Color(255, 255, 255));
        btn_0.setText("0");
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_0MouseClicked(evt);
            }
        });
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        btn_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_0KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_0KeyTyped(evt);
            }
        });
        jPanel1.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 50));

        btn_resu.setBackground(new java.awt.Color(102, 102, 102));
        btn_resu.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_resu.setForeground(new java.awt.Color(255, 255, 255));
        btn_resu.setText("=");
        btn_resu.setFocusPainted(false);
        btn_resu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resuMouseClicked(evt);
            }
        });
        btn_resu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_resu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 50, 50));

        btn_punto1.setBackground(new java.awt.Color(0, 0, 0));
        btn_punto1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_punto1.setForeground(new java.awt.Color(255, 255, 255));
        btn_punto1.setText(".");
        btn_punto1.setFocusPainted(false);
        btn_punto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_punto1MouseClicked(evt);
            }
        });
        btn_punto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_punto1ActionPerformed(evt);
            }
        });
        btn_punto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_punto1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_punto1KeyReleased(evt);
            }
        });
        jPanel1.add(btn_punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 50));

        btn_division.setBackground(new java.awt.Color(0, 0, 0));
        btn_division.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_division.setForeground(new java.awt.Color(255, 255, 255));
        btn_division.setText("/");
        btn_division.setFocusPainted(false);
        btn_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_divisionMouseClicked(evt);
            }
        });
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 70, 50));

        btn_suma.setBackground(new java.awt.Color(0, 0, 0));
        btn_suma.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_suma.setForeground(new java.awt.Color(255, 255, 255));
        btn_suma.setText("+");
        btn_suma.setFocusPainted(false);
        btn_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sumaMouseClicked(evt);
            }
        });
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 70, 50));

        btn_multipli.setBackground(new java.awt.Color(0, 0, 0));
        btn_multipli.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_multipli.setForeground(new java.awt.Color(255, 255, 255));
        btn_multipli.setText("x");
        btn_multipli.setFocusPainted(false);
        btn_multipli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multipli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_multipliMouseClicked(evt);
            }
        });
        btn_multipli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multipliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_multipli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, 50));

        btn_resta.setBackground(new java.awt.Color(0, 0, 0));
        btn_resta.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_resta.setForeground(new java.awt.Color(255, 255, 255));
        btn_resta.setText("-");
        btn_resta.setFocusPainted(false);
        btn_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_restaMouseClicked(evt);
            }
        });
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("C");
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 140, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("AC");
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -30, -1, 30));

        txt_r.setBackground(new java.awt.Color(255, 255, 0));
        txt_r.setForeground(new java.awt.Color(255, 255, 255));
        txt_r.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_r.setFocusable(false);
        jPanel1.add(txt_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        txt_r1.setBackground(new java.awt.Color(255, 255, 0));
        txt_r1.setForeground(new java.awt.Color(255, 255, 255));
        txt_r1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_r1.setFocusable(false);
        jPanel1.add(txt_r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 20));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Ayuda");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 350));

        jPanel3.setBackground(new java.awt.Color(25, 26, 28));

        txtresultado.setBackground(new java.awt.Color(255, 255, 255));
        txtresultado.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtresultado.setForeground(new java.awt.Color(255, 255, 255));
        txtresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtoperacion.setBackground(new java.awt.Color(25, 26, 28));
        txtoperacion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        txtoperacion.setForeground(new java.awt.Color(255, 255, 255));
        txtoperacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtoperacion.setBorder(null);
        txtoperacion.setOpaque(true);
        txtoperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoperacionActionPerformed(evt);
            }
        });
        txtoperacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtoperacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoperacionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtresultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtoperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(txtoperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void son(){
AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Eje_calculadora/efecto de sonido beep.wav"));
        sonido.play();}

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
         if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "1";
        }else{
            cadenaNumeros += "1";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; //voy a usar la calculadora
      
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseClicked
        son();
        
        
    }//GEN-LAST:event_btn_1MouseClicked

    private void btn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseClicked
        son();
    }//GEN-LAST:event_btn_2MouseClicked

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
       if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "2";
        }else{
            cadenaNumeros += "2";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
       
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MouseClicked
        son();
    }//GEN-LAST:event_btn_3MouseClicked

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "3";
        }else{
            cadenaNumeros += "3";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
        
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseClicked
        son();
    }//GEN-LAST:event_btn_4MouseClicked

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
       if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "4";
        }else{
            cadenaNumeros += "4";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
        
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseClicked
       son();
    }//GEN-LAST:event_btn_5MouseClicked

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
      if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "5";
        }else{
            cadenaNumeros += "5";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
        
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseClicked
       son();
    }//GEN-LAST:event_btn_6MouseClicked

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "6";
        }else{
            cadenaNumeros += "6";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseClicked
        son();
    }//GEN-LAST:event_btn_7MouseClicked

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "7";
        }else{
            cadenaNumeros += "7";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseClicked
        son();
    }//GEN-LAST:event_btn_8MouseClicked

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "8";
        }else{
            cadenaNumeros += "8";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseClicked
        son();
    }//GEN-LAST:event_btn_9MouseClicked

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
     if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "9";
        }else{
            cadenaNumeros += "9";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_0MouseClicked
        son();
    }//GEN-LAST:event_btn_0MouseClicked

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        if(txtoperacion.getText().equals("0")){
            cadenaNumeros = "0";
        }else{
            cadenaNumeros += "0";
        }     
        txtoperacion.setText(cadenaNumeros);
        activado = true; 
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_resuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resuMouseClicked
        son();
    }//GEN-LAST:event_btn_resuMouseClicked

    private void btn_resuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resuActionPerformed
    double segundoNumero;
        if(operacion.equals("nula")){
            txtoperacion.setText(cadenaNumeros);
        }
        
        else if(operacion.equals("sumar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;;
            txt_r.setVisible(false);
            txt_r1.setVisible(false);
            txt_r.setText(Double.toString(primerNumero)+" + ");
            txt_r1.setText(Double.toString(segundoNumero));
            txtoperacion.setText(String.format("% .2f",resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        else if(operacion.equals("restar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;;
            txt_r.setVisible(false);
            txt_r1.setVisible(false);
            txt_r.setText(Double.toString(primerNumero)+" - ");
            txt_r1.setText(Double.toString(segundoNumero));
            txtoperacion.setText(String.format("% .2f",resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        
        else if(operacion.equals("multiplicar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;;
            txt_r.setVisible(false);
            txt_r1.setVisible(false);
            txt_r.setText(Double.toString(primerNumero)+" x ");
            txt_r1.setText(Double.toString(segundoNumero));
            txtoperacion.setText(String.format("% .2f",resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        else if (operacion.equals("dividir")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            if (segundoNumero == 0) {
                txtoperacion.setText("NoSeDividePor0");
            } else {
                resultado = primerNumero / segundoNumero;;
                txt_r.setVisible(false);
            txt_r1.setVisible(false);
            txt_r.setText(Double.toString(primerNumero)+" / ");
            txt_r1.setText(Double.toString(segundoNumero));
                txtoperacion.setText(String.format("% .2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            }
        }
        
        txtresultado.setText("");
        activado = true;
        punto = false;
       
        ar();
             
    }//GEN-LAST:event_btn_resuActionPerformed

    private void btn_punto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_punto1MouseClicked
        son();
    }//GEN-LAST:event_btn_punto1MouseClicked

    private void btn_punto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_punto1ActionPerformed
        
           if(punto == true){
            if(cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
            }else{
                cadenaNumeros += ".";
            }
            txtoperacion.setText(cadenaNumeros);
            punto = false;
        } 
    }//GEN-LAST:event_btn_punto1ActionPerformed

    private void btn_divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_divisionMouseClicked
        son();
    }//GEN-LAST:event_btn_divisionMouseClicked

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        // TODO add your handling code here:
         if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "dividir";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sumaMouseClicked
        son();
    }//GEN-LAST:event_btn_sumaMouseClicked

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "sumar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_multipliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multipliMouseClicked
       son();
    }//GEN-LAST:event_btn_multipliMouseClicked

    private void btn_multipliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multipliActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
            operacion = "multiplicar";
            
            activado = false;
            punto = true;
          
        }
    }//GEN-LAST:event_btn_multipliActionPerformed

    private void btn_restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restaMouseClicked
        son();
    }//GEN-LAST:event_btn_restaMouseClicked

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
         if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
            operacion = "restar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_restaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtresultado.setText("");
        txtoperacion.setText("0");
        operacion = "nula";
        cadenaNumeros = "";
        activado = true;
        punto = true;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int tamaño = cadenaNumeros.length(); 
        if(tamaño > 0){
            if(tamaño == 1){
                cadenaNumeros = "0";
            }else{
                cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length() - 1);
            }
            txtoperacion.setText(cadenaNumeros);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        son();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       son();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btn_0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_0KeyTyped
  
    }//GEN-LAST:event_btn_0KeyTyped

    private void btn_0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_0KeyPressed
     
      
    }//GEN-LAST:event_btn_0KeyPressed

    private void txtoperacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoperacionKeyReleased
        // TODO add your handling code here:
        do{
        
        
        switch (evt.getKeyCode()) {
            
            case KeyEvent.VK_0 -> {
                
                if (txtoperacion.getText().equals("0")) {
                    
                    cadenaNumeros = "0";
                } else {
                    cadenaNumeros += "0";
                }
                txtoperacion.setText(cadenaNumeros);
                activado = true;
                btn_0.setBackground(Color.black);
                son();
                }
            case KeyEvent.VK_1 -> {
                if (txtoperacion.getText().equals("0")) {
                    cadenaNumeros = "1";
                } else {
                    cadenaNumeros += "1";
                }   txtoperacion.setText(cadenaNumeros);
                activado = true;
                btn_1.setBackground(Color.black);
                son();
                }
            case KeyEvent.VK_2 -> {
                if (txtoperacion.getText().equals("0")) {
                    cadenaNumeros = "2";
                } else {
                    cadenaNumeros += "2";
                }   txtoperacion.setText(cadenaNumeros);
                activado = true;
                btn_2.setBackground(Color.black);
                son();
                }
                case KeyEvent.VK_3 -> {
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "3";
                    } else {
                        cadenaNumeros += "3";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_3.setBackground(Color.black);
                    son();
                }
                case KeyEvent.VK_4 -> {
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "4";
                    } else {
                        cadenaNumeros += "4";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_4.setBackground(Color.black);
                    son();
                }
                
                case KeyEvent.VK_5 -> {
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "5";
                    } else {
                        cadenaNumeros += "5";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_5.setBackground(Color.black);
                    son();
                }
                
                case KeyEvent.VK_6 -> {
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "6";
                    } else {
                        cadenaNumeros += "6";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_6.setBackground(Color.black);
                    son();
                }
                 
              
                
                case KeyEvent.VK_8 -> {
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "8";
                    } else {
                        cadenaNumeros += "8";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_8.setBackground(Color.black);
                    son();
                }
                
                case KeyEvent.VK_9 -> {
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "9";
                    } else {
                        cadenaNumeros += "9";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_9.setBackground(Color.black);
                    son();
                }
                
                case KeyEvent.VK_MINUS -> {
                    if(activado == true){
                        primerNumero = Double.parseDouble(cadenaNumeros);
                        txtresultado.setText(cadenaNumeros + " - ");
                        cadenaNumeros = "";
                        operacion = "restar";
                        
                        activado = false;
                        punto = true;
                    }
                    btn_resta.setBackground(Color.black);
                    son();
                }
                
                
                   case KeyEvent.VK_ENTER -> {
                       double segundoNumero;
                       if(operacion.equals("nula")){
                           txtoperacion.setText(cadenaNumeros);
                       }
                       
                       
                       
                       else if(operacion.equals("sumar")){
                           segundoNumero = Double.parseDouble(cadenaNumeros);
                           resultado = primerNumero + segundoNumero;;
                           txtoperacion.setText(String.format("% .2f",resultado));
                           cadenaNumeros = String.valueOf(resultado);
                           operacion = "nula";
                       }
                       else if(operacion.equals("restar")){
                           segundoNumero = Double.parseDouble(cadenaNumeros);
                           resultado = primerNumero - segundoNumero;;
                           txtoperacion.setText(String.format("% .2f",resultado));
                           cadenaNumeros = String.valueOf(resultado);
                           operacion = "nula";
                       }
                       
                       else if(operacion.equals("multiplicar")){
                           segundoNumero = Double.parseDouble(cadenaNumeros);
                           resultado = primerNumero * segundoNumero;;
                           txtoperacion.setText(String.format("% .2f",resultado));
                           cadenaNumeros = String.valueOf(resultado);
                           operacion = "nula";
                       }
                       else if (operacion.equals("dividir")) {
                           segundoNumero = Double.parseDouble(cadenaNumeros);
                           if (segundoNumero == 0) {
                               txtoperacion.setText("NoSeDividePor0");
                           } else {
                               resultado = primerNumero / segundoNumero;;
                               txtoperacion.setText(String.format("% .2f", resultado));
                               cadenaNumeros = String.valueOf(resultado);
                               operacion = "nula";
                           }
                       }
                       
                       txtresultado.setText("");
                       activado = true;
                       punto = false;
                       
                       btn_resu.setBackground(Color.black);
                       son();
                }
                
            
        }
        if(evt.getKeyChar()=='/'){
             if(activado == true){
                 
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "dividir";
            
            activado = false;
            punto = true;
        }
         btn_division.setBackground(Color.black);
         son(); 
        }else if(evt.getKeyChar()=='*'){
             if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
            operacion = "multiplicar";
            
            activado = false;
            punto = true;
        } btn_multipli.setBackground(Color.black);
         son(); 
         }else if(evt.getKeyChar()=='+'){
             if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            txtresultado.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "sumar";
            
            activado = false;
            punto = true;
        } btn_suma.setBackground(Color.black);
         son(); 
         }else if(evt.getKeyChar()=='.'){
              if(punto == true){
            if(cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
            }else{
                cadenaNumeros += ".";
            }
            txtoperacion.setText(cadenaNumeros);
            punto = false;
        } btn_punto1.setBackground(Color.black);
        son();
         
         }else if(evt.getKeyChar()=='7'){
         
                    if (txtoperacion.getText().equals("0")) {
                        cadenaNumeros = "7";
                    } else {
                        cadenaNumeros += "7";
                    }   txtoperacion.setText(cadenaNumeros);
                    activado = true;
                    btn_7.setBackground(Color.black);
                    son();
                
                
         }
        
        }while(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE);
    }//GEN-LAST:event_txtoperacionKeyReleased

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        btn_1.setBackground(Color.cyan);
        
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseReleased
       
        try {
            TimeUnit.MILLISECONDS.sleep(300);
             btn_1.setBackground(Color.BLACK);
        } catch (InterruptedException ex) {
          
        }
       
        
    }//GEN-LAST:event_btn_1MouseReleased

    private void btn_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_1KeyPressed
  
        

        
    }//GEN-LAST:event_btn_1KeyPressed

    private void txtoperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoperacionActionPerformed
        // TODO add your handling code here:
        
     
        
    }//GEN-LAST:event_txtoperacionActionPerformed

    private void btn_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1KeyReleased

    private void txtoperacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoperacionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_0 ){
           
               btn_0.setBackground(Color.white);      
            
        }else if(evt.getKeyCode()==KeyEvent.VK_1 ){
           
                 btn_1.setBackground(Color.white); 
            
        }else if(evt.getKeyCode()==KeyEvent.VK_2 ){
           
                 btn_2.setBackground(Color.white); 
            
          
        }else if(evt.getKeyCode()==KeyEvent.VK_3 ){
           
                 btn_3.setBackground(Color.white); 
            
            
        }else if(evt.getKeyCode()==KeyEvent.VK_4 ){
           
                 btn_4.setBackground(Color.white); 
            
            
        }else if(evt.getKeyCode()==KeyEvent.VK_5 ){
           
                 btn_5.setBackground(Color.white); 
            
            
        }else if(evt.getKeyCode()==KeyEvent.VK_6 ){
           
                 btn_6.setBackground(Color.white); 
            
            
        }else  
            if(evt.getKeyCode()==KeyEvent.VK_8 ){
           
                 btn_8.setBackground(Color.white); 
            
            
        }else if(evt.getKeyCode()==KeyEvent.VK_9 ){
           
                 btn_9.setBackground(Color.white); 
            
            
        }else  if(evt.getKeyCode()==KeyEvent.VK_MINUS ){
           
                 btn_resta.setBackground(Color.white); 
            
         
        
                
        }else if(evt.getKeyChar()=='/'){
        btn_division.setBackground(Color.white);
        }else if(evt.getKeyChar()=='*'){
        btn_multipli.setBackground(Color.white);
        }else if(evt.getKeyChar()=='+' ){
           
                 btn_suma.setBackground(Color.white);  
        }else if(evt.getKeyChar()=='.' ){
           
                 btn_punto1.setBackground(Color.white);  
        }else if(evt.getKeyChar()=='7'){
           
                 btn_7.setBackground(Color.white); 
            
            
        }else  if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                 btn_resu.setBackground(Color.white); }
    }//GEN-LAST:event_txtoperacionKeyPressed

    private void btn_punto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_punto1KeyPressed
      
    }//GEN-LAST:event_btn_punto1KeyPressed

    private void btn_punto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_punto1KeyReleased
   
      
    }//GEN-LAST:event_btn_punto1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        JOptionPane.showMessageDialog(null, "            Instrucciones para uso de la calculadora\n "
            + "Instrucciones de uso para para la calculadora:\n"
            + "1.En la pantalla se muestra los digitos\ndel 0 al 9 para realizar operaciones basicas\n"
            + "2.Se puede realizar la accion de seleccionar los datos\n  mediante teclaso y mouse   \n"
            + "3.Para utilizar la mutiplicacion mediante el teclado es Shift+*                      \n"
            + "4.Para utilizar la division mediante teclado Shift + 7                               \n"
            + "5.Para dar el resultado precione la tecla Enter                                      \n"
            + "6.El punto puede ser precionado solo una vez \n no puede poner doble punto\n\n"
            + " "
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calculadora().setVisible(true);
            }
        });
    }

    public void addNumber(String digito){
    txtoperacion.setText(txtoperacion.getText()+digito);
    }
    public void Enter(){
    btn_1.setBackground(Color.white);}
     
    public void ar() {
     
   try{
      
   FileWriter fichero =new FileWriter("C:\\Users\\mutsu\\OneDrive\\Documentos\\NetBeansProjects\\Eje_calculadora\\archivos\\bitacoraCalculadora.txt");

   fichero.write(txt_r.getText()  + txt_r1.getText() + " = " + txtoperacion.getText() );
   fichero.write("");
  
   fichero.close();
    
 
   }catch(IOException e){} 
   }
 
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_multipli;
    private javax.swing.JButton btn_punto1;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_resu;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel txt_r;
    private javax.swing.JLabel txt_r1;
    private javax.swing.JTextField txtoperacion;
    private javax.swing.JLabel txtresultado;
    // End of variables declaration//GEN-END:variables
}
